name: Unit Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "**/*.md"

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
          
      - name: Install protoc
        run: sudo apt install -y protobuf-compiler

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install gRPC Go plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

      - name: Generate pb.go and build
        run: make all

      - name: Test
        run: go test -v ./...