name: Unit Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "**/*.md"

jobs:
  build-win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      - name: Install make
        run: choco install make

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Install proto-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      
      - name: Install gRPC Go plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

      - name: Generate pb.go and build
        run: make all

      - name: Test
        run: make test
  build-unix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    steps:
      - uses: actions/checkout@v2
          
      - name: Install protoc
        run: sudo apt install -y protobuf-compiler

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Install gRPC Go plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

      - name: Generate pb.go and build
        run: make all

      - name: Test
        run: make test