name: Unit Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "**/*.md"

jobs:
  build-win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      - name: Install make
        run: choco install make

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Install proto-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      
      - name: Install gRPC Go plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

      - name: Test
        run: make test

      - name: Change Cross-Platform badge on fail
        if: ${{ failure() }}
        run: |
          sed -i "" 's/linux-brightgreen/linux-red/g' README.md
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Clement Jean'
            git config --global user.email 'Clement-Jean@users.noreply.github.com'
            git add README.md
            git commit -m "Cross-Platform build failed"
            git push
          fi
      - name: Change Cross-Platform badge on success
        if: ${{ success() }}
        run: |
          sed -i "" 's/linux-red/linux-brightgreen/g' README.md
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Clement Jean'
            git config --global user.email 'Clement-Jean@users.noreply.github.com'
            git add README.md
            git commit -m "Cross-Platform build succeeded"
            git push
          fi
  build-unix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    steps:
      - uses: actions/checkout@v2
          
      - name: Install Protoc
        run: apt install protobuf
        # uses: arduino/setup-protoc@v1
        # with:
        #   version: '3.x'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Install gRPC Go plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

      - name: Test
        run: make test

      - name: Change Cross-Platform badge on fail
        if: ${{ failure() }}
        run: |
          sed -i "" 's/linux-brightgreen/linux-red/g' README.md
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Clement Jean'
            git config --global user.email 'Clement-Jean@users.noreply.github.com'
            git add README.md
            git commit -m "Cross-Platform build failed"
            git push
          fi
      - name: Change Cross-Platform badge on success
        if: ${{ success() }}
        run: |
          sed -i "" 's/linux-red/linux-brightgreen/g' README.md
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Clement Jean'
            git config --global user.email 'Clement-Jean@users.noreply.github.com'
            git add README.md
            git commit -m "Cross-Platform build succeeded"
            git push
          fi