name: Go Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache protobuf library
        id: cache-protobuf
        uses: actions/cache@v1
        with:
          path: protobuf
          key: ${{ runner.os }}-protobuf

      - name: Build protobuf library
        if: steps.cache-protobuf.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/protocolbuffers/protobuf.git
          cd protobuf
          git submodule update --init --recursive
          ./autogen.sh
          ./autogen.sh
          ./configure
          make
          make check
          
      - name: Install protobuf library
        run: |
          cd protobuf
          sudo make install
          sudo ldconfig 

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Generate pb.go
        run: |
          cd greet && protoc proto/*.proto --go-grpc_out=. --go_out=.
          cd calculator && protoc proto/*.proto --go-grpc_out=. --go_out=.
          cd blog && protoc proto/*.proto --go-grpc_out=. --go_out=.

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...