name: Unit Tests

on:
  push:
    branches: [ master ]
    paths:
      - "**/*.go"
      - "**/*.proto"
  pull_request:
  branches: [ master ]
    paths:
      - "**/*.go"
      - "**/*.proto"

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
          
      - name: Install protoc
        run: sudo apt install -y protobuf-compiler

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install gRPC Go plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

      - name: Generate pb.go
        run: |
          cd greet && protoc proto/*.proto --go_opt=module=github.com/Clement-Jean/grpc-go-course --go-grpc_out=. --go_out=. && cd ..
          cd calculator && protoc proto/*.proto --go_opt=module=github.com/Clement-Jean/grpc-go-course --go-grpc_out=. --go_out=. && cd ..
          cd blog && protoc proto/*.proto --go_opt=module=github.com/Clement-Jean/grpc-go-course --go-grpc_out=. --go_out=. && cd ..

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...